%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.1

-ifndef(protos).
-define(protos, true).

-define(protos_gpb_version, "4.4.1").

-ifndef('INTMESSAGE_PB_H').
-define('INTMESSAGE_PB_H', true).
-record('IntMessage',
        {value                  :: integer()        % = 1, 32 bits
        }).
-endif.

-ifndef('SERVERRESPONSE_PB_H').
-define('SERVERRESPONSE_PB_H', true).
-record('ServerResponse',
        {userId                 :: integer(),       % = 1, 32 bits
         response               :: iolist() | undefined, % = 2
         error                  :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('AUTHENTICATION_PB_H').
-define('AUTHENTICATION_PB_H', true).
-record('Authentication',
        {credentialsType        :: 'REGISTER' | 'LOGIN' | integer(), % = 1, enum Authentication.CredentialsType
         userType               :: 'INVESTOR' | 'COMPANY' | integer(), % = 2, enum Authentication.UserType
         username               :: iolist(),        % = 3
         password               :: iolist()         % = 4
        }).
-endif.

-ifndef('MSGCOMPANY_PB_H').
-define('MSGCOMPANY_PB_H', true).
-record('MsgCompany',
        {companyId              :: integer() | undefined, % = 1, 32 bits
         type                   :: 'FIXEDRATE' | 'AUCTION' | integer(), % = 2, enum MsgCompany.Type
         amount                 :: integer(),       % = 3, 32 bits
         rate                   :: float() | integer() | infinity | '-infinity' | nan | undefined % = 4
        }).
-endif.

-ifndef('MSGINVESTOR_PB_H').
-define('MSGINVESTOR_PB_H', true).
-record('MsgInvestor',
        {investorId             :: integer() | undefined, % = 1, 32 bits
         company                :: integer(),       % = 2, 32 bits
         amount                 :: integer(),       % = 3, 32 bits
         rate                   :: float() | integer() | infinity | '-infinity' | nan | undefined % = 4
        }).
-endif.

-ifndef('MSGEXCHANGE_PB_H').
-define('MSGEXCHANGE_PB_H', true).
-record('MsgExchange',
        {type                   :: 'COMPANY' | 'INVESTOR' | integer(), % = 1, enum MsgExchange.Type
         company                :: protos:'MsgCompany'() | undefined, % = 2
         investor               :: protos:'MsgInvestor'() | undefined % = 3
        }).
-endif.

-ifndef('NOTIFICATION_PB_H').
-define('NOTIFICATION_PB_H', true).
-record('Notification',
        {company                :: integer(),       % = 1, 32 bits
         message                :: iolist()         % = 2
        }).
-endif.

-endif.
